import type { Metadata } from "next";
import "./globals.css";
// import { Header } from "@/components/header";
// import { Navigation } from "@/components/navigation";
// import { GlobalStyles } from "@/theme/globals";
// import Providers from "./styled-providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">  
      <body>
        {children}
      </body>
    </html>
  )
}
